version: '3.9'

services:
  client:
    container_name: prakticum-client
    image: ghcr.io/mind-blowing-devs/mind-blowing-devs/client:9a3b27ac941a569eda69822762c82d3e4ac0680e
    restart: always
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - CLIENT_PORT=5000
      - SERVER_PORT=5001
      - EXTERNAL_SERVER_URL=http://158.160.81.49:5001
      - INTERNAL_SERVER_URL=http://prakticum-server:5001
      - ORIGIN_DEV_URL=http://localhost:5000
      - ORIGIN_PROD_URL=http://158.160.81.49:5000
    networks:
      - practicum-network
  server:
    container_name: prakticum-server
    image: ghcr.io/mind-blowing-devs/mind-blowing-devs/server:9a3b27ac941a569eda69822762c82d3e4ac0680e
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - '5001:5001'
    environment:
      SERVER_PORT: 5001
      REDIS_PORT: 6379
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      EXTERNAL_SERVER_URL: http://158.160.81.49:5001
      INTERNAL_SERVER_URL: http://prakticum-server:5001
      ORIGIN_DEV_URL: http://localhost:5000
      ORIGIN_PROD_URL: http://158.160.81.49:5000
    networks:
      - postgres-network
      - practicum-network

    command: sh -c "./wait-for.sh postgres:5432 --
      ./wait-for.sh redis:6379 --
      node /app/src/index.js"

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 5466
    ports:
      - '5466:5466'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres-network

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - practicum-network

networks:
  practicum-network:
    driver: bridge
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
  redis-data:
