version: '3.9'

services:
  client:
    container_name: prakticum-client
    image: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME/client:TAG # Замените на актуальную ссылку на образ
    restart: always
    ports:
      - '5000:80'
    environment:
      - CLIENT_PORT=5000
      - SERVER_PORT=5001

  server:
    container_name: prakticum-server
    image: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME/server:TAG # Замените на актуальную ссылку на образ
    restart: always
    ports:
      - '5001:5001'
    environment:
      - SERVER_PORT=5001
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
